
app = "peliprex-31wrsa"
primary_region = "scl"

[build]
  builder = "paketobuildpacks/builder-jammy-base"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ["app"]

[[mounts]]
  source = "peliprex_data"
  destination = "/data"
