# fly.toml app configuration file para peliprex
app = 'peliprex'
primary_region = 'iad'

[build]

[mounts]
  source = "peliculas_tal"
  destination = "/app/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory_mb = 2048
  cpu_kind = 'shared'
  cpus = 1
